spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  security:
    user:
      password: Test12345
  sql:
    init:
      platform: postgres

jwt:
  secret: atifimalcom
  expirationMs: 86400000