spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver
  security:
    user:
      password: Test12345
  sql:
    init:
      platform: postgres

jwt:
  secret: c547455a1a9be3b7823119f5e9e3a742fa18a6b6b6e43992bdd756d05655d1d5c547455a1a9be3b7823119f5e9e3a742fa18a6b6b6e43992bdd756d05655d1d5
  expirationMs: 86400000